# Generated by Django 5.2.4 on 2025-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_A", models.CharField(max_length=25)),
                ("team_B", models.CharField(max_length=25)),
                ("noOfOvers", models.PositiveIntegerField()),
                ("toss", models.CharField(max_length=25)),
                ("battingFirst", models.CharField(max_length=25)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
